site_name: Battlefleet
theme:
  name: material
  palette:
    - scheme: default
      primary: blue grey
      accent: amber
      toggle:
        icon: material/toggle-switch
    - scheme: slate
      primary: blue grey
      accent: amber
      toggle:
        icon: material/toggle-switch-off-outline
  custom_dir: overrides
  logo: assets/image--004.png
  favicon: assets/favicon.ico
  features:  
    - navigation.indexes
    - navigation.tabs
    - navigation.top
extra:
  generator: false
markdown_extensions:
  - md_in_html
  - tables
  - attr_list
  - toc:
      permalink: true
      toc_depth: 4

validation:
  absolute_links: ignore

nav:
  - Home:
    - Home: index.md
  - The Rules:
    - The Rules: the-rules.md
  - The Turn:
    - The Turn: the-turn.md
  - The Movement Phase:
    - The Movement Phase: the-movement-phase.md
  - The Shooting Phase:
    - The Shooting Phase: the-shooting-phase.md
  - The Ordnance Phase:
    - The Ordnance Phase: the-ordnance-phase.md
  - The End Phase:
    - The End Phase: the-end-phase.md
  - Squadrons:
    - Squadrons: squadrons.md
  - Planetary Defences:
    - Planetary Defences: planetary-defences.md
  - The Battlefield:
    - The Battlefield: the-battlefield.md
  - Scenarios:
    - Scenarios: scenarios.md
  - Campaign Rules:
    - Campaign Rules: campaign-rules.md
  - Gothic Sector:
    - Gothic Sector: gothic-sector.md
  - The Third Armageddon War:
    - The Third Armageddon War: the-third-armageddon-war.md
  - "Abaddon's 13th Black Crusade":
    - "Abaddon's 13th Black Crusade": abaddons-13th-black-crusade.md
  - "Andy Chambers' Notes":
    - "Andy Chambers' Notes": andy-chambers-notes.md

