site_name: Battlefleet
theme:
  name: material
  palette:
    - scheme: default
      primary: blue grey
      accent: amber
      toggle:
        icon: material/toggle-switch
    - scheme: slate
      primary: blue grey
      accent: amber
      toggle:
        icon: material/toggle-switch-off-outline
  custom_dir: overrides
  logo: assets/image--004.png
  favicon: assets/favicon.ico
  features:  
    - header.autohide
    - navigation.indexes
    - navigation.tabs
    - navigation.top
extra:
  generator: false
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - md_in_html
  - tables
  - pymdownx.details
  - pymdownx.tilde
  - attr_list
  - pymdownx.snippets:
      auto_append:
        - includes/footnotes.md
validation:
  absolute_links: ignore

nav:
  - What You Will Need:
    - What You Will Need: what-you-will-need.md
  - The Turn:
    - The Turn: the-turn.md
  - The Movement Phase:
    - The Movement Phase: the-movement-phase.md
  - The Shooting Phase:
    - The Shooting Phase: the-shooting-phase.md
  - The Ordnance Phase:
    - The Ordnance Phase: the-ordnance-phase.md
  - The End Phase:
    - The End Phase: the-end-phase.md
  - Squadrons:
    - Squadrons: squadrons.md
  - Planetary Defences:
    - Planetary Defences: planetary-defences.md



