site_name: Battlefleet

theme:
  name: material
  palette:
    - scheme: default
      primary: blue grey
      accent: amber
      toggle:
        icon: material/toggle-switch
    - scheme: slate
      primary: blue grey
      accent: amber
      toggle:
        icon: material/toggle-switch-off-outline
  custom_dir: overrides
  logo: assets/image--004.png
  favicon: assets/favicon.png
  features:  
    - navigation.indexes
    - navigation.tabs
    - navigation.top
extra:
  generator: false

extra_css:
  - assets/extra.css

markdown_extensions:
  - md_in_html
  - tables
  - attr_list
  - toc:
      permalink: true
      toc_depth: 4

validation:
  absolute_links: ignore

nav:
  - Home:
    - Home: index.md
    - Introduction: the-rules.md
    - The Turn: the-turn.md
    - The Movement Phase: the-movement-phase.md
    - The Shooting Phase: the-shooting-phase.md
    - The Ordnance Phase: the-ordnance-phase.md
    - The End Phase: the-end-phase.md
    - Squadrons: squadrons.md
    - Planetary Defences: planetary-defences.md
    - The Battlefield: the-battlefield.md
    - Scenarios: scenarios.md
    - Campaign Rules: campaign-rules.md
    - The Third Armageddon War: the-third-armageddon-war.md
    - "Abaddon's 13th Black Crusade": abaddons-13th-black-crusade.md
    - "Andy Chambers' Notes": andy-chambers-notes.md
    - Colophon: colophon.md
  - Introduction:
    - Introduction: the-rules.md
  - The Turn:
    - The Turn: the-turn.md
  - The Movement Phase:
    - The Movement Phase: the-movement-phase.md
  - The Shooting Phase:
    - The Shooting Phase: the-shooting-phase.md
  - The Ordnance Phase:
    - The Ordnance Phase: the-ordnance-phase.md
  - The End Phase:
    - The End Phase: the-end-phase.md
  - Squadrons:
    - Squadrons: squadrons.md
  - Planetary Defences:
    - Planetary Defences: planetary-defences.md
  - The Battlefield:
    - The Battlefield: the-battlefield.md
  - Scenarios:
    - Scenarios: scenarios.md
    - "Scenario One: Cruiser Clash": scenarios/cruiser-clash.md
    - "Scenario Two: The Bait": scenarios/the-bait.md
    - "Scenario Three: The Raiders": scenarios/the-raiders.md
    - "Scenario Four: Surprise Attack": scenarios/surprise-attack.md
    - "Scenario Five: Blockade Run": scenarios/blockade-run.md
    - "Scenario Six: Convoy": scenarios/convoy.md
    - "Scenario Seven: Planetary Assault": scenarios/planetary-assault.md
    - "Scenario Eight: Escalating Engagement": scenarios/escalating-engagement.md
    - "Scenario Nine: Exterminatus": scenarios/exterminatus.md
    - "Scenario Ten: Fleet Engagement": scenarios/fleet-engagement.md
  - Campaign Rules:
    - Campaign Rules: campaign-rules.md
  - The Third Armageddon War:
    - The Third Armageddon War: the-third-armageddon-war.md
    - "Scenario One: The Gauntlet": the-third-armageddon-war/the-gauntlet.md
    - "Scenario Two: Parol’s Bait": the-third-armageddon-war/parols-bait.md
    - "Scenario Three: Pelucidar": the-third-armageddon-war/pelucidar.md

  - "Abaddon's 13th Black Crusade":
    - "Abaddon's 13th Black Crusade": abaddons-13th-black-crusade.md
    - "Scenario One: Chance Encounter": abaddons-13th-black-crusade/chance-encounter.md
    - "Scenario Two: Rearguard Attack": abaddons-13th-black-crusade/rearguard-attack.md
    - "Scenario Three: Alien Intervention": abaddons-13th-black-crusade/alien-intervention.md
    - "Scenario Four: Above Belis Corona": abaddons-13th-black-crusade/above-belis-corona.md
    - "Scenario Five: Daemon Blockade": abaddons-13th-black-crusade/daemon-blockade.md
    - "Scenario Six: Navigate the Storm": abaddons-13th-black-crusade/navigate-the-storm.md
    - "Scenario Seven: Macharia's End": abaddons-13th-black-crusade/macharias-end.md

  - "Andy Chambers' Notes":
    - "Andy Chambers' Notes": andy-chambers-notes.md
  - Colophon:
    - Colophon: colophon.md
