name: ci 
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      pages: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - run: pip install mkdocs-material 

      - run: mkdocs build

      - uses: actions/configure-pages@v6

      - uses: actions/upload-pages-artifact@v4
        with:
          path: site/

      - uses: actions/deploy-pages@v5
